export const CREATE_QRCODE_REQUEST = 'CREATE_QRCODE_REQUEST'
export const CREATE_QRCODE_SUCCESS = 'CREATE_QRCODE_SUCCESS'
export const CREATE_QRCODE_FAIL = 'CREATE_QRCODE_FAIL'
export const CREATE_QRCODE_RESET = 'CREATE_QRCODE_RESET'

export const GET_ALL_QRCODE_REQUEST = 'GET_ALL_QRCODE_REQUEST'
export const GET_ALL_QRCODE_SUCCESS = 'GET_ALL_QRCODE_SUCCESS'
export const GET_ALL_QRCODE_FAIL = 'GET_ALL_QRCODE_FAIL'

export const GET_ID_QRCODE_REQUEST = 'GET_ID_QRCODE_REQUEST'
export const GET_ID_QRCODE_SUCCESS = 'GET_ID_QRCODE_SUCCESS'
export const GET_ID_QRCODE_FAIL = 'GET_ID_QRCODE_FAIL'

export const GENERATE_QRCODE_REQUEST = 'GENERATE_QRCODE_REQUEST'
export const GENERATE_QRCODE_SUCCESS = 'GENERATE_QRCODE_SUCCESS'
export const GENERATE_QRCODE_FAIL = 'GENERATE_QRCODE_FAIL'
