export const TEBAK_NOMOR_REQUEST = 'TEBAK_NOMOR_REQUEST'
export const TEBAK_NOMOR_SUCCESS = 'TEBAK_NOMOR_SUCCESS'
export const TEBAK_NOMOR_FAIL = 'TEBAK_NOMOR_FAIL'
export const TEBAK_NOMOR_RESET = 'TEBAK_NOMOR_RESET'
